### ISSUE TITLE
Task: Setup backend for Connecting with GitHub API

### ISSUE THREAD

**Issue by JakobMckenna** [JakobMckenna/NoName#12]
Will need to connect to the GitHub API with an API token and parse the data

**Comment by TehillahK** [comment]
created github routes

1)  **http:// localhost:5000/github/branches/:owner/:repo**
- req params: owner , repo
- gets all branches currently open on a repo

2) **http:// localhost:5000/github/commits/:owner/:repo**
- req params: owner , repo
- gets all commits made on the main github branch

3) **http://localhost:5000/github/commits/branch/:owner/:repo/:branch**
- req params: owner , repo , branch
- gets all commits made on a certain

4) **http://localhost:5000/github/latestcommits/:owner/:repo/:branch**
- req params: owner , repo , branch
- gets all commits made on a certain branch within the past hour


5) **http://localhost:5000/github/issues/:owner/:repo**
- req params: owner , repo 
- gets all issues

6) **http://localhost:5000/github/closedissues/:owner/:repo**
- req params: owner ,  repo
- gets all  issues closed within the past hour

7) **http://localhost:5000/github/pulls/:owner/:repo**
- req params: owner ,  repo
- gets all pull requests on a repo

completed in 2 days spent 2 hours on day 1 and 3 hours on day 2 , completed on October 4th
